routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LogbookController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\ProfileController;
use App\Models\Pendaftaran;
use Illuminate\Support\Facades\Route;

require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('home')->middleware(['auth']);

Route::middleware(['auth', 'verified'])->group(function () {

    Route::get('/profile', [ProfileController::class, 'profile'])->name('profile');
    Route::post('/profile', [ProfileController::class, 'update_profile'])->name('profile');
    
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/logbook', [LogbookController::class, 'index'])->name('logbook');
    Route::post('/logbook/json', [LogbookController::class, 'json_data'])->name('logbook.json');
    Route::get('/logbook/tambah', [LogbookController::class, 'create'])->name('logbook.create');
    Route::post('/logbook/simpan', [LogbookController::class, 'store'])->name('logbook.store');
    Route::get('/logbook/edit/{id}', [LogbookController::class, 'edit'])->name('logbook.edit');
    Route::post('/logbook/update', [LogbookController::class, 'update'])->name('logbook.update');
    Route::get('/logbook/export/{any}', [LogbookController::class, 'export'])->name('logbook.export');
    Route::post('/logbook/delete', [LogbookController::class, 'destroy'])->name('logbook.destroy');

    Route::prefix('pendaftaran')->name('pendaftaran.')->group(function () {
        Route::get('/', [PendaftaranController::class, 'index'])->name('list');
        Route::get('/create', [PendaftaranController::class, 'create'])->name('create');
        Route::post('/store', [PendaftaranController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [PendaftaranController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [PendaftaranController::class, 'update'])->name('update');
        Route::delete('/destroy/{id}', [PendaftaranController::class, 'destroy'])->name('destroy');
        Route::post('/json', [PendaftaranController::class, 'json'])->name('json');
    });

    Route::group(['middleware' => 'guards'], function() {

        Route::get('/users', [UsersController::class, 'index'])->name('users');
        Route::post('/users/list', [UsersController::class, 'list'])->name('users.list');
        Route::get('/users/create', [UsersController::class, 'create'])->name('users.create');
        Route::post('/users/store', [UsersController::class, 'store'])->name('users.store');
        Route::get('/users/edit/{id}', [UsersController::class, 'edit'])->name('users.edit');
        Route::post('/users/update', [UsersController::class, 'update'])->name('users.update');
        Route::post('/users/delete', [UsersController::class, 'destroy'])->name('users.delete');
        Route::get('/users/activation/{id}', [UsersController::class, 'activation'])->name('users.activation');

    });
});

Route::get('/terms', [PageController::class, 'terms'])->name('terms');

app/Models/Pendaftaran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pendaftaran extends Model
{
    use HasFactory;

    protected $table = "pendaftaran";

    protected $fillable = [
        'user_id', 'jurusan_id', 'name', 'email', 'telp', 'address', 'gender'
    ];

    public function jurusan()
    {
        return $this->hasOne(Jurusan::class, 'id', 'jurusan_id');
    }

}

app/Http/Controllers/PendaftaranController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PendaftaranRequest;
use App\Models\Jurusan;
use App\Models\Pendaftaran;
use App\Services\PendaftaranService;
use Illuminate\Http\Request;

class PendaftaranController extends Controller
{

    private function getListJurusan()
    {
        $list_jurusan = [];
        foreach(Jurusan::all() as $value) {
            $list_jurusan[$value['id']] = $value['name'];
        }
        return $list_jurusan;
    }

    private function getListGender()
    {
        return [
            'L' => 'Laki-laki',
            'P' => 'Perempuan'
        ];
    }

    public function index() 
    {
        return view('pendaftaran.index');
    }

    public function json(Request $request, PendaftaranService $pendaftaranService)
    {
        $data = [];

        $no = intval($request['start']);
        $start = intval($request['start']);
        $length = intval($request['length']);
        $filter = "";

        if ( isset($request['start']) && $request['length'] != -1 ) {

            $start = intval($request['start']);
            $length = intval($request['length']);
        }

        if ( isset($request['search']) && $request['search']['value'] != '' ) {
            $filter = trim($request['search']['value']);
        }

        $daftar = $pendaftaranService->getAllDataPendaftaran($filter)
                            ->orderBy('id','desc')
                            ->skip($start)
                            ->take($length)
                            ->get();      
        
        $total_record_filter = $pendaftaranService->getAllDataPendaftaran()->count();

        $data = [];

        foreach ($daftar as $value) {
            ++$no;
            $value->no = $no;
            $value->jurusan = $value->jurusan->name;
            $value->edit = route('pendaftaran.edit', ['id' => $value->id]);
            $value->delete = route('pendaftaran.destroy', ['id' => $value->id]);
            $data[] = $value;    
        }

        die(json_encode([
            "draw"            => isset ( $request['draw'] ) ? intval( $request['draw'] ) : 0,
            "recordsTotal"    => intval( ( $total_record_filter ) ),
            "recordsFiltered" => intval( ( $total_record_filter ) ),
            'data' => $data
        ]));
    }

    public function create()
    {
        $jurusan = $this->getListJurusan();

        $gender = $this->getListGender();

        return view('pendaftaran.create', compact('jurusan', 'gender'));
    }

    public function store(PendaftaranRequest $request, PendaftaranService $pendaftaranService)
    {
        $create = $pendaftaranService->create($request->all());
        if ($create) {
            return redirect()->route('pendaftaran.list')->with(['success' => 'Pendaftaran Berhasil.']);
        } else { 
            return redirect()->route('pendaftaran.create')->withInput()->withErrors(['error' => 'Ada kesalahan. Silahkan coba beberapa saat lagi.']);
        }

    }

    public function edit($id)
    {
        $jurusan = $this->getListJurusan();

        $gender = $this->getListGender();

        $daftar = Pendaftaran::findOrfail($id);

        return view('pendaftaran.edit', compact('jurusan', 'gender', 'daftar'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'id'        => ['required'],
            'jurusan'   => ['required'],
            'name'      => ['required'],
            'gender'    => ['required'],
            'telp'      => ['required'],
            'email'     => ['required', 'email'],
            'address'   => ['required']
        ]);

        $update = Pendaftaran::where([
            'id'        => $request->id,
            'user_id'   => auth()->user()->id
        ])
        ->update([
            'user_id'       => auth()->user()->id,
            'jurusan_id'    => $request->jurusan,
            'name'          => $request->name,
            'gender'        => $request->gender,
            'telp'          => $request->telp,
            'email'         => $request->email,
            'address'       => $request->address
        ]);

        if ($update) {
            return redirect()->route('pendaftaran.list')->with(['success' => 'Ubah Pendaftaran Berhasil.']);
        } else { 
            return redirect()->route('pendaftaran.edit', ['id' => $id])->withInput()->withErrors(['error' => 'Ada kesalahan. Silahkan coba beberapa saat lagi.']);
        }
    }

    public function destroy($id)
    {
        $delete = Pendaftaran::findOrfail($id);
        $delete->delete();
        if($delete) {
            return response()->json(['response' => 'Pendaftaran Berhasil Dihapus'], 200);
        } else {
            return response()->json(['response' => 'Pendaftaran Gagal Dihapus'], 422);
        }
    }

    public function hitung()
    {
        return 3 + 5;
    }
}

resources/views/pendaftaran/create.blade.php
@extends('layout')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h5>Tambah Pendaftaran</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    @error('error')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                    <form method="post" action="{{ route('pendaftaran.store') }}">
                        @csrf
                        <div class="form-group">
                            {!! eform_select('Jurusan', 'jurusan', $jurusan, old('jurusan')) !!}
                            @error('jurusan')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Nama Lengkap', 'name', old('name') ?? auth()->user()->name) !!}
                            @error('name')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_select('Jenis Kelamin', 'gender', $gender, old('gender')) !!}
                            @error('gender')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Telp. (Mobile)', 'telp', old('telp')) !!}
                            @error('telp')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Email', 'email', old('email') ?? auth()->user()->email) !!}
                            @error('email')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Alamat', 'address', old('address'), '') !!}
                            @error('address')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div>
                            <a href="{{ route('pendaftaran.list') }}" class="btn btn-danger">Kembali</a>
                            <button type="submit" class="btn btn-primary">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
$('form').on('submit', function(e) {
    $('a, button').addClass('disabled', true).attr('disabled', true)
})
</script>
@endpush

resources/views/pendaftaran/edit.blade.php
@extends('layout')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h5>Ubah Pendaftaran</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    @error('error')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                    <form method="post" action="{{ route('pendaftaran.update', $daftar['id']) }}">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="id" value="{{ $daftar['id'] }}">
                        <div class="form-group">
                            {!! eform_select('Jurusan', 'jurusan', $jurusan, old('jurusan') ?? $daftar['jurusan_id']) !!}
                            @error('jurusan')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Nama Lengkap', 'name', old('name') ?? $daftar['name']) !!}
                            @error('name')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_select('Jenis Kelamin', 'gender', $gender, old('gender') ?? $daftar['gender']) !!}
                            @error('gender')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Telp. (Mobile)', 'telp', old('telp') ?? $daftar['telp']) !!}
                            @error('telp')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Email', 'email', old('email') ?? $daftar['email']) !!}
                            @error('email')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div class="form-group">
                            {!! eform_input('text', 'Alamat', 'address', old('address') ?? $daftar['address'], '') !!}
                            @error('address')
                            <div class="invalid-feedback" style="display: block;">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>

                        <div>
                            <a href="{{ route('pendaftaran.list') }}" class="btn btn-danger">Kembali</a>
                            <button type="submit" class="btn btn-primary">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
$('form').on('submit', function(e) {
    $('a, button').addClass('disabled', true).attr('disabled', true)
})
</script>
@endpush

resources/views/pendaftaran/index.blade.php
@extends('layout')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <h5>Pendaftaran</h5>
        </div>
        <div class="col-lg-4">
            <div class="pull-right mb-2">
                <a href="{{ route('pendaftaran.create') }}" class="btn btn-sm btn-primary">
                    Tambah
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
            @endif
            <div class="card">
                <div class="card-body">
                   
                    <div class="table-responsive">
                        <table class="table table-bordered mb-0">
                            <thead>
                                <tr>
                                    <th style="width: 2%;">No</th>
                                    <th style="width: 15%;">Nama</th>
                                    <th style="width: 8%;">Telp. (Mobile)</th>
                                    <th style="width: 10%;">Email</th>
                                    <th>Alamat</th>
                                    <th style="width: 7%;">Jenis Kelamin</th>
                                    <th style="width: 10%;">Jurusan</th>
                                    <th style="width: 7%;">Opsi</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
function btnDelete(url) {
    var konfirm = confirm("Anda yakin akan menghapus data ini?")
    if (konfirm) {
        $.ajax({
            url: url,
            type: 'delete',
            dataType: 'json',
            success:function(res) {
                window.location.reload()
            },
            error: function(error) {
                alert(error)
            }
        })
    } else {
        return false
    }
}

var table = $('.table').DataTable({
    ordering: false,
    serverSide: true,
    processing: true,
    // fixedHeader: true,
    responsive: true,
    stateSave: true,
    ajax: {
        url: "{{ route('pendaftaran.json') }}",
        type: 'post',
        data: {
            status: $('#status').val()
        }
    },
    columns: [
        { "data": "no", sClass: "text-center" },
        { "data": "name" },
        { "data": "telp", sClass: "text-center" },
        { "data": "email" },
        { "data": "address" },
        { "data": "gender", sClass: "text-center" },
        { "data": "jurusan.name" },
        {
            "data": null,
            sClass: "text-center",
            render: function(data, type, row, meta) {
                return `
                        <a class="btn btn-sm btn-success" href="${data.edit}"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-sm btn-danger" onclick="btnDelete('${data.delete}')"><i class="fa fa-trash"></i></a>
                    `
            }
        },
    ],
    initComplete: function() {
        var api = this.api();
        $("input[type='search']")
            .off(".DT")
            .on("keyup.DT, blur", function(e) {
                if (e.keyCode === 13) {
                    api.search(this.value).draw();
                }
            });
        $("input[type='search']").attr('placeholder', 'Press Enter to search')
    },
})


</script>
@endpush